
server:
  port: 8012

spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AyushmanRavan/configurations.git
          cloneOnStart: true
          username: AyushmanRavan
          password: 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
          search-paths: abc-service-api
          default-label: master

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
